### ISSUE TITLE
endgame doesn't end anything ?

### ISSUE THREAD

**Issue by toqix** [Qrashi/InvasionBW#11]
after typing /endgame and confirming it says "A game end token was generated", but after waiting for over two minutes still nothing happens the only thing I noticed is the action bar starting to show another thing for 1sec and then the normal bar again.

**Comment by Fritz-CO-KG** [comment]
bruh

**Comment by Fritz-CO-KG** [comment]
You have to type it twice, the frist time it is just to CONFIRM

**Comment by Fritz-CO-KG** [comment]
See #6

**Comment by Fritz-CO-KG** [comment]
pepega
